global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules

remote_write:
- url: http://mimir:8080/api/v1/push

scrape_configs:

- job_name: prometheus
  scrape_interval: 10s
  static_configs:
  - targets: ['localhost:9090']

- job_name: mimir
  scrape_interval: 10s
  static_configs:
  - targets: ['mimir:8080']

- job_name: grafana
  scrape_interval: 10s
  static_configs:
  - targets: ['grafana:3000']

- job_name: loki
  scrape_interval: 10s
  static_configs:
  - targets: ['loki:3100']

- job_name: fluentbit
  scrape_interval: 10s
  metrics_path: /api/v1/metrics/prometheus
  scheme: http
  static_configs:
  - targets: ['fluentbit:2020']

- job_name: minio
  scrape_interval: 10s
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['minio:9000']

- job_name: 'activemq'
  scrape_interval: 5s
  static_configs:
  - targets: ['telegraf:9273']

#rule_files:
#- alert.yml

#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets: [ 'alertmanager:9093' ]
