{
 "title": "ActiveMQ Demo",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values(activemq_queues_enqueue_count,name)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(activemq_queues_enqueue_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queue Size",
   "type": "timeseries",
   "description": "Curent size of queue",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "activemq_queues_size{job=\"$job\",name=~\"$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Consumers",
   "type": "timeseries",
   "description": "Active consumers on queue",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "activemq_queues_consumer_count{job=\"$job\",name=~\"$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Enqueued",
   "type": "timeseries",
   "description": "Total items equeued",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "activemq_queues_enqueue_count{job=\"$job\",name=~\"$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Dequeued",
   "type": "timeseries",
   "description": "Total items dequeued",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "activemq_queues_dequeue_count{job=\"$job\",name=~\"$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Enqueue rate (5m)",
   "type": "timeseries",
   "description": "Rate of items added to queue",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(activemq_queues_enqueue_count{job=\"$job\",name=~\"$queue\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Dequeue rate (5m)",
   "type": "timeseries",
   "description": "Rate of dequed items",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "rate(activemq_queues_dequeue_count{job=\"$job\",name=~\"$queue\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}