---
apiVersion: 1

deleteDatasources:
- name: Prometheus
- name: Mimir
- name: Loki

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  access: proxy
  editable: false
  isDefault: true

- name: Mimir
  type: prometheus
  url: http://mimir:8080/prometheus
  access: proxy
  editable: false

- name: Loki
  type: loki
  url: http://loki:3100
  access: proxy
  editable: false
